### PR TITLE
Implement GET_TIP_FORMING and SET_TIP_FORMING

### PR DESCRIPTION
**Pull request by rschaeuble**
These commands allow to view and update the tip forming configuration at runtime.

## Major Changes in this PR
Implement GET_TIP_FORMING and SET_TIP_FORMING, so that the tip forming configuration can be viewed and updated at runtime.

## How the changes in this PR are tested
Manually

## PR Checklist: (Checked-off items are either done or do not apply to this PR)
 
- [X] I have performed a self-review of my code
- [x] CHANGELOG.md is updated (if end-user facing)
- [ ] Sent notification to software-design channel requesting review

### CODE REVIEW

**Comment by rschaeuble** [comment]
I don't know why generate_docs.py made so many changes and why it doesn't pick of the correct usage documentation. I can undo the changes to that file is requested.

**Comment by ejsears** [comment]
> I don't know why generate_docs.py made so many changes and why it doesn't pick of the correct usage documentation. I can undo the changes to that file is requested.

It probably wasn't run on the last merge to main. I'm pretty sure it is case sensitive when it is looking for `Usage` vice `USAGE` in your code.

**Comment by rschaeuble** [comment]
I changed USAGE to Usage and now the docs are good, too.

**Comment by rschaeuble** [comment]
I can't send a notification to the software-design channel, though, as I don't see it in the channels list on Discord.

**Review by jimmyjon711 — APPROVED** [review]

**Pull request merged**
